name: assistive_vqa
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - pillow
  - tqdm
  - pyyaml
  - jupyter
  - ipykernel
  - pip
  - pip:
      - transformers
      - timm
      - opencv-python
      - albumentations
      - seaborn
      - evaluate
      - sentencepiece
      - accelerate